### PR TITLE
Add basic task submit statistics

### PR DESCRIPTION
**Pull request by Kobzol**
TODO:
- [x] where to put links? TaskEdit for task and TaskDetails for assignments (teacher only)?
- [x] what to add to the page?

Closes https://github.com/mrlvsb/kelvin/issues/24

### CODE REVIEW

**Review by trnila — APPROVED** [review]
je to super!:)

**Review by geordi — APPROVED** [review]
Very nice!

**Comment by geordi** [comment]
I pushed a super minor change...

**Comment by geordi** [comment]
At some point, it would be nice to have [Sparkline](https://en.wikipedia.org/wiki/Sparkline) somewhere in the teachers view.

**Pull request merged**
