### PR TITLE
Fix for overlapping comments #175

### PR DESCRIPTION
**Pull request by tomasmensik**

### CODE REVIEW

**Comment by tomasmensik** [comment]
Before: https://ctrlv.link/M7AM
After: https://ctrlv.link/12cQ

**Comment by tomasmensik** [comment]
Before: https://ctrlv.link/8uU2
After: https://ctrlv.link/bqMh

**Comment by geordi** [comment]
Please, remove the Merge commit.

**Comment by trnila** [comment]
It would be better to replace absolute positioning of icons with flexbox so it is not so fragile in case we change width of page or we add new icon...

**Pull request closed without merging**
